### ISSUE TITLE
"No gulpfile found"

### ISSUE THREAD

**Issue by mmoravec** [CityOfZion/cityofzion.github.io#21]
Unclear instructions in the readme. Did the steps but I'm getting "No gulpfile found".

**Comment by canesin** [comment]
@mmoravec we need to change the README, this is now only the compiled website. The sources are in github.com/cityofzion/website.
@revett help with the README ?

**Comment by revett** [comment]
Yep - can help 🎉

**Comment by revett** [comment]
README updated to help with confusion in #22.
